name: Unreal Plugin Build and Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "main"
  workflow_dispatch:

env:
  ENGINE_PATH: ${{ secrets.ENGINE_PATH }}
  PLUGIN_NAME: "FalloutCore"
  BADGE_PATH: "./badges"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Plugin
        id: build
        shell: cmd
        continue-on-error: true
        run: |
          set UAT="%ENGINE_PATH%\Engine\Build\BatchFiles\RunUAT.bat"
          call %UAT% BuildPlugin -plugin="${{github.workspace}}/FalloutCore.uplugin" -package="./PackagedPlugin"

      - name: Generate Build Status Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 1ecc5322c5f14f2d9b769a82f6793e60
          filename: unreal_plugin_build_status.json
          label: build
          message: ${{ steps.build.outcome == 'success' && 'passing' || 'failing' }}
          color: ${{ steps.build.outcome == 'success' && 'success' || 'critical' }}

      - name: Create ZIP Archive
        if: steps.build.outcome == 'success' && startsWith(github.ref, 'refs/tags/')
        run: |
          Compress-Object -Path "./PackagedPlugin" -DestinationPath "./${{ env.PLUGIN_NAME }}.zip"
        shell: pwsh

      - name: Create Release
        if: steps.build.outcome == 'success' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./${{ env.PLUGIN_NAME }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Build Status
        if: steps.build.outcome != 'success'
        run: |
          echo "Build failed!"
          exit 1